# https://github.com/walkiop/compose/edit/master/docker-compose.yaml 
version: '3'
services:

  api:
    image: walkio/compose_api
    ports:
      - "4000:5000"
    depends_on:
      - mysql
    deploy:
      replicas: 3
      mode: replicated
      restart_policy:
        condition: on-failure


  mysql:
    image: walkio/compose_mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: senhaFib
       MYSQL_USER: root
       MYSQL_DATABASE: fibonaccidb
